### PR TITLE
Added experience section

### PR DESCRIPTION
**Pull request by VIKAS0264**
Screenshot (6)

### CODE REVIEW

**Comment by VIKAS0264** [comment]
Experience section has been added, if you want me to make any changes please tell me.

**Comment by everly-gif** [comment]
Please send an updated screenshot, we recently had another section added to the website,( get in touch section) make sure that changes are updated in your PR

**Comment by VIKAS0264** [comment]
Sure.

**Comment by VIKAS0264** [comment]
hey @everly-gif since get in touch section was created before experience section the background of the section is white but experience section should be above get in touch section now it breaks the pattern please give me input to what to do regarding this
Screenshot (8)
see the above image both of the sections background color is white

**Comment by everly-gif** [comment]
I'm merging it now , I will create a new issue for this asking for someone to fix the colors of get in touch section

**Comment by everly-gif** [comment]
I have to revert this, it's breaking everything of the page from navbar, project section , experience section etc

**Comment by VIKAS0264** [comment]
@everly-gif you merged the pr which i had not updated give me a chance i will correct everything.

**Pull request merged**
