### PR TITLE
Made a new form and also added a hover effect to the link button

### PR DESCRIPTION
**Pull request by Satya-Chandana**
image

### CODE REVIEW

**Comment by Satya-Chandana** [comment]
Do check it now

**Comment by Satya-Chandana** [comment]
Best Basic Portfolio Template 2021 and 1 more page - Profile 1 - Microsoft​ Edge 24-10-2021 21_44_34 (2)

**Comment by everly-gif** [comment]
this PR has merge conflicts, pls resolve them , rest looks good

**Comment by Satya-Chandana** [comment]
Yes, I  have Removed conflicts.

**Comment by rajmunkhan** [comment]
@Satya-Chandana the design is good but see how the footer came inside the form. and the form isn't in the middle of the page. Can u plz make it correct

**Comment by rajmunkhan** [comment]
The screenshot you attached looks different than the actual site became. plz rectify the changes if you can.

**Comment by Satya-Chandana** [comment]
image

I still find mine is perfectly alright.. I'll still check and modify the issue.

**Comment by Satya-Chandana** [comment]
https://github.com/rajmunkhan/basic-portfolio-template/pull/94 
please check this pull request. I hope this wont show that error.

**Pull request merged**
