### PR TITLE
Add Hover Effect for Navigation Bar

### PR DESCRIPTION
**Pull request by nishant-giri**
## Related Issue
Fixed Issue #23.

## Proposed Changes
- Updated [style.css](https://github.com/rajmunkhan/basic-portfolio-template/blob/master/css/style.css) by adding hover effect for navigation bar.
- Updated [index.html](https://github.com/rajmunkhan/basic-portfolio-template/blob/master/index.html) with minor changes.

## Screenshot
image

### CODE REVIEW

**Comment by nishant-giri** [comment]
Sure, I'm attaching the screenshot.

**Comment by rajmunkhan** [comment]
@nishant-giri brother, its style is same only, u just changed the background color and the color doesn't match the theme also. Can u plz do something different?

**Comment by piyush999-o** [comment]
Sir,
I added Navbar hover effect and commit all changes. Please see this and how
can i resend pull request. ❤️

**Comment by rajmunkhan** [comment]
@nishant-giri make the background color light blue and text color white on hover

**Comment by nishant-giri** [comment]
## Updated Screenshot
image

@rajmunkhan, I've made the required changes.

**Comment by nishant-giri** [comment]
@rajmunkhan, could you kindly review the changes? Do inform me if any further changes are required.

**Pull request closed without merging**
